{ ... }: {
  programs.nixvim = {
    opts = {
      autoindent = true; # auto-indent new lines
      autochdir = true; # change current directory to the file's directory
      backspace = "indent,eol,start"; # allow backspace on indent, end of line, and start
      breakindent = true; # wrapped lines will be indented
      backup = false; # no backup files
      completeopt = "menu,menuone,noinsert,fuzzy,popup,noselect"; # completion options
      completeitemalign = "kind,abbr,menu"; # align completion items
      relativenumber = false; # show absolute line numbers

      colorcolumn = "100"; # highlight column 100
      # cmdheight = 1;                        # more space in the neovim command line for displaying messages
      clipboard = "unnamedplus"; # use system clipboard
      confirm = true; # confirm before quitting with unsaved changes
      cursorline = true; # highlight current line
      cursorcolumn = false; # do not highlight current column
      copyindent = true; # copy indentation from previous line
      conceallevel = 0; # so that `` is visible in markdown files
      expandtab = true; # use spaces instead of tabs
      fileencoding = "utf-8"; # the encoding written to a file
      foldtext = ""; # use default fold text
      foldlevelstart = 99; # start with all folds open
      foldmethod = "expr"; # use expression for folding
      foldexpr = "v:lua.vim.treesitter.foldexpr()"; # treesitter folding expression
      hidden = true; # hide buffers instead of closing them
      history = 1000; # number of commands to remember in history
      hlsearch = true; # highlight search matches
      inccommand = "split"; # show search and replace results in a split
      ignorecase = true; # ignore case in search
      linebreak = true; # wrap lines at word boundaries
      laststatus = 3; # always show status line
      magic = true; # use magic characters in regex
      mouse = "a"; # enable mouse in all modes
      numberwidth = 4; # set number column width to 2 {default 4}
      number = true; # show line numbers
      list = true; # show invisible characters
      listchars = {
        tab = "▸ ";
        trail = " ";
        # eol = "↵";
        space = " ";
        nbsp = "␣";
        extends = "⟩";
        precedes = "⟦";
      };
      pumheight = 15; # pop up menu height
      pumwidth = 30; # pop up menu width
      preserveindent = true; # preserve indentation
      ruler = false; # do not show ruler
      sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"; # session options
      showtabline = 1; # 1: Show tabs from 2+ open ones, 2: always show tabs
      showcmd = false; # do not show command in the last line
      showmode = false; # do not show mode
      scrolloff = 2; # keep 2 lines above and below cursor
      sidescrolloff = 5; # keep 5 columns left and right of cursor
      shortmess = "aoOTIcF"; # shorten messages
      showmatch = true; # show matching brackets
      signcolumn = "yes"; # always show sign column
      smarttab = true; # smart tabbing
      smoothscroll = true; # smooth scrolling
      splitbelow = true; # new horizontal splits go below
      splitright = true; # new vertical splits go right
      swapfile = false; # no swap files
      smartindent = true; # smart autoindenting for C-like programs
      smartcase = true; # override 'ignorecase' if search pattern contains uppercase letters
      shiftwidth = 4; # number of spaces for indentation
      synmaxcol = 240; # max column for syntax highlighting
      termguicolors = false; # do not use GUI colors in terminal
      textwidth = 80; # max width of text
      tabstop = 4; # number of spaces a tab counts for
      timeout = true; # enable timeout for key codes
      ttimeout = true; # enable timeout for key codes in terminal
      timeoutlen = 500; # timeout length in milliseconds
      ttimeoutlen = 10; # timeout length for terminal key codes in milliseconds
      updatetime = 1000; # time in ms for CursorHold event
      undofile = true; # Build-in persistent undo
      virtualedit = "block"; # allow cursor to move where there is no text in block visual mode
      writebackup = false; # no backup before writing
      wildignorecase = true; # ignore case when completing file names
      winborder = "rounded"; # rounded window borders
      wrap = false; # do not wrap lines
    };
  };
}
